name: Docker Image CI

on:
  schedule: [ cron: "0 2 * * 2" ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dmglab/webvirtcloud:${{ steps.vars.outputs.short_ref }}
