name: Docker Image CI

on:
  schedule: [ cron: "0 2 * * 1-5" ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dmglab/webvirtcloud:pipe-${GITHUB_SHA:0:8}
